@url_api=http://localhost:8081/v1/api/

## User Sign up
POST {{url_api}}/signup
Content-Type: application/json

{
    "name": "oke1",
    "email": "trannhutphattv@gmail.com",
    "address": "HCM",
    "phone": "0393372222",
    "password": "password123"
}